# Generated by Django 4.2.16 on 2024-10-06 13:53

from django.db import migrations, models
import theater.models


class Migration(migrations.Migration):

    dependencies = [
        ("theater", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="play",
            name="image",
            field=models.ImageField(
                null=True, upload_to=theater.models.play_image_path
            ),
        ),
    ]
